### ISSUE TITLE
Why is the version in the maven rep 0.5.1 while 0.1.1 in master branch?

### ISSUE THREAD

**Issue by misssprite** [RedisLabs/spark-redis#21]
And I found the maven dependency disappears in the README.md.

**Comment by sunheehnus** [comment]
Hi @misssprite , the former `rep 0.5.1` is not clearly thinked over during coding, and @itamarhaber bumped it to `0.1.1` which makes more sense :-)

**Comment by misssprite** [comment]
Hi @sunheehnus 
But version 0.1.1 seems not in the maven rep, does it?
Is it possible to add dependency using sbt or maven?

**Comment by sunheehnus** [comment]
http://spark-packages.org/package/RedisLabs/spark-redis , you can find it here :-)

**Comment by misssprite** [comment]
Thanks for the information. But I still have some problems.
The version 0.1.1 on spark-packages.org is not updated with the master branch on github.
That page gives the following link, and the interface is not compatible with the latest one on github.
For example, `sc.toRedisKV(stringRDD)` is not available.
https://github.com/RedisLabs/spark-redis/tree/5dd370f0655986d6a4fa45c41fa3772d9f5f0b21

**Comment by sunheehnus** [comment]
Hi @misssprite , the APIs have changed a little bit so that we don't need to include redis endpoint(host, ip) every time. Currently, we didn't release a new version of spark-redis with that changes, and still some more features need to be merged before releasing, such as the ZSetRDD, spark streaming, etc. So if you want to use the current APIs, you need to download the library's source and build it:
git clone https://github.com/RedisLabs/spark-redis.git
cd spark-redis
mvn clean package -DskipTests

Thanks for reporting :-)

**Comment by misssprite** [comment]
Got it. Thanks for your patience. @sunheehnus

**Comment by sunheehnus** [comment]
Thanks @misssprite
